name: ilri01
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - requests
  - pandas
  - pyyaml
  - tqdm
  - python-dotenv
  - rich
  - matplotlib
  - seaborn      
  - openpyxl     
  - python-docx
  - pillow
  - pip:
      - typer>=0.9
      - reportlab