name: ilri01
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - requests
  - pandas
  - pyyaml
  - tqdm
  - python-dotenv
  - rich
  - matplotlib
  - seaborn      # Added for Step 6 Heatmaps
  - openpyxl     # Added for Step 6 Excel Export
  - pip:
      - typer>=0.9